namespace Models
{
    public class NXLibraryEnums
    {
        public enum Genre
        {
            Fiction,
            NonFiction,
            Mystery,
            Thriller,
            Fantasy,
            ScienceFiction,
            Biography,
            History,
            Romance,
            Horror,
            SelfHelp,
            Health,
            Travel,
            Guide,
            Religion,
            Science,
            Poetry,
            Encyclopedia,
            Dictionary,
            Comics,
            Art,
            Cookbooks,
            Diaries,
            Journals,
            Series,
            Trilogy,
            Drama,
            Adventure,
            Children,
            Crime,
            Fairytale,
            GraphicNovel,
            HistoricalFiction,
            Memoir,
            Philosophy
        }
    }
}
