@NX_Library_Backend_HostAddress = http://localhost:5002

GET {{NX_Library_Backend_HostAddress}}/todos/
Accept: application/json

###

GET {{NX_Library_Backend_HostAddress}}/todos/1
Accept: application/json

###
